services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      # HA web UI on the server (LAN / VPN)
      - "8123:8123"
    networks:
      - ha-argus
    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  ha-argus:
    name: ha-argus
